[project]
name = "streamlit-template"
version = "0.1.0"
description = "Template streamlit app for Eigenscribe Inc."
requires-python = ">=3.11"
dependencies = [
    "streamlit>=1.44.1",
    "ipython>=9.1.0",
    "matplotlib>=3.10.1",
    "networkx>=3.4.2",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "plotly>=6.0.1",
    "scipy>=1.15.2",
    "sqlalchemy>=2.0.40",
    "trafilatura>=2.0.0",
    "pytest",
    "black",
    "ruff",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[project.optional-dependencies]
dev = ["pytest", "ruff", "mypy", "pre-commit", "ipykernel"]